/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReplayRouteImport } from './routes/_app.replay'
import { Route as AppProofsRouteImport } from './routes/_app.proofs'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppOracleRouteImport } from './routes/_app.oracle'
import { Route as AppMatchesRouteImport } from './routes/_app.matches'
import { Route as AppMarketsRouteImport } from './routes/_app.markets'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppMatchesIdRouteImport } from './routes/_app.matches.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AppProofsRoute = AppProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOracleRoute = AppOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketsRoute = AppMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesIdRoute = AppMatchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/markets': typeof AppMarketsRoute
  '/matches': typeof AppMatchesRouteWithChildren
  '/oracle': typeof AppOracleRoute
  '/portfolio': typeof AppPortfolioRoute
  '/proofs': typeof AppProofsRoute
  '/replay': typeof AppReplayRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/matches/$id': typeof AppMatchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/markets': typeof AppMarketsRoute
  '/matches': typeof AppMatchesRouteWithChildren
  '/oracle': typeof AppOracleRoute
  '/portfolio': typeof AppPortfolioRoute
  '/proofs': typeof AppProofsRoute
  '/replay': typeof AppReplayRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/matches/$id': typeof AppMatchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/markets': typeof AppMarketsRoute
  '/_app/matches': typeof AppMatchesRouteWithChildren
  '/_app/oracle': typeof AppOracleRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/proofs': typeof AppProofsRoute
  '/_app/replay': typeof AppReplayRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/matches/$id': typeof AppMatchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/leaderboard'
    | '/markets'
    | '/matches'
    | '/oracle'
    | '/portfolio'
    | '/proofs'
    | '/replay'
    | '/settings'
    | '/tasks'
    | '/matches/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/leaderboard'
    | '/markets'
    | '/matches'
    | '/oracle'
    | '/portfolio'
    | '/proofs'
    | '/replay'
    | '/settings'
    | '/tasks'
    | '/matches/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/markets'
    | '/_app/matches'
    | '/_app/oracle'
    | '/_app/portfolio'
    | '/_app/proofs'
    | '/_app/replay'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/matches/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/replay': {
      id: '/_app/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proofs': {
      id: '/_app/proofs'
      path: '/proofs'
      fullPath: '/proofs'
      preLoaderRoute: typeof AppProofsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oracle': {
      id: '/_app/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof AppOracleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches': {
      id: '/_app/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/markets': {
      id: '/_app/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof AppMarketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matches/$id': {
      id: '/_app/matches/$id'
      path: '/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof AppMatchesIdRouteImport
      parentRoute: typeof AppMatchesRoute
    }
  }
}

interface AppMatchesRouteChildren {
  AppMatchesIdRoute: typeof AppMatchesIdRoute
}

const AppMatchesRouteChildren: AppMatchesRouteChildren = {
  AppMatchesIdRoute: AppMatchesIdRoute,
}

const AppMatchesRouteWithChildren = AppMatchesRoute._addFileChildren(
  AppMatchesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMarketsRoute: typeof AppMarketsRoute
  AppMatchesRoute: typeof AppMatchesRouteWithChildren
  AppOracleRoute: typeof AppOracleRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProofsRoute: typeof AppProofsRoute
  AppReplayRoute: typeof AppReplayRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMarketsRoute: AppMarketsRoute,
  AppMatchesRoute: AppMatchesRouteWithChildren,
  AppOracleRoute: AppOracleRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProofsRoute: AppProofsRoute,
  AppReplayRoute: AppReplayRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
