/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StadiumRouteImport } from './routes/stadium'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PredictRouteImport } from './routes/predict'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as IndexRouteImport } from './routes/index'

const StadiumRoute = StadiumRouteImport.update({
  id: '/stadium',
  path: '/stadium',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictRoute = PredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moments': typeof MomentsRoute
  '/passport': typeof PassportRoute
  '/predict': typeof PredictRoute
  '/rewards': typeof RewardsRoute
  '/stadium': typeof StadiumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moments': typeof MomentsRoute
  '/passport': typeof PassportRoute
  '/predict': typeof PredictRoute
  '/rewards': typeof RewardsRoute
  '/stadium': typeof StadiumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/moments': typeof MomentsRoute
  '/passport': typeof PassportRoute
  '/predict': typeof PredictRoute
  '/rewards': typeof RewardsRoute
  '/stadium': typeof StadiumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/moments' | '/passport' | '/predict' | '/rewards' | '/stadium'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/moments' | '/passport' | '/predict' | '/rewards' | '/stadium'
  id:
    | '__root__'
    | '/'
    | '/moments'
    | '/passport'
    | '/predict'
    | '/rewards'
    | '/stadium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MomentsRoute: typeof MomentsRoute
  PassportRoute: typeof PassportRoute
  PredictRoute: typeof PredictRoute
  RewardsRoute: typeof RewardsRoute
  StadiumRoute: typeof StadiumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stadium': {
      id: '/stadium'
      path: '/stadium'
      fullPath: '/stadium'
      preLoaderRoute: typeof StadiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predict': {
      id: '/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof PredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MomentsRoute: MomentsRoute,
  PassportRoute: PassportRoute,
  PredictRoute: PredictRoute,
  RewardsRoute: RewardsRoute,
  StadiumRoute: StadiumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
